### ISSUE TITLE
Map vs For Loop

### ISSUE THREAD

**Issue by mark-bradshaw** [hapijs/accept#12]
Determine if there is a significant speed difference in node, and if so, convert functional style implementations to more classic flow control.

**Comment by mark-bradshaw** [comment]
Per @nlf in #11, for is definitely faster in recent benchmarks, so I'll need to go back and pull out the functional stuff where I can.

**Comment by Marsup** [comment]
What did you decide about this ?

**Comment by mark-bradshaw** [comment]
Seems a non-issue.  Far as I know none of the new accept header methods are being used in Hapi, and there's no push to make any alteration.  The functionality is just fine, and unless this starts getting used in a hot-path, I don't see it as being much of an issue.  I'm open to the change, but less and less interested in that sort of tuning without good reason.
