### ISSUE TITLE
Media type based on preferences

### ISSUE THREAD

**Issue by sholladay** [hapijs/accept#19]
For my [error transformation](https://github.com/hapijs/hapi/blob/master/API.md#error-transformation) plugin, [hapi-error-page](https://github.com/sholladay/hapi-error-page), I need to be sure to respect the client's desired media type, taking into account its [q weightings](https://tools.ietf.org/html/rfc7231#section-5.3.2).

I expected there to be a method for this, since such a thing exists for all of the other header types, but that doesn't seem to be the case.

Similar to the other methods, the signature would be `mediaType(mediaTypeHeader, [preferences])`.

**Comment by hueniverse** [comment]
It exists for the other headers because someone needed those and added them...

**Comment by sholladay** [comment]
Absolutely! Just wanted to be clear on my thought process / justification.

I'm actually surprised no one has needed this yet. I can't be the only one. 😀 

Anyway, I would be super grateful if someone more familiar here could help. But if not, I will happily find the time to make a PR.

**Comment by mark-bradshaw** [comment]
I'd be happy to help out but I'm on paternity leave right now. I'm afraid I have little time and brain power left over at the moment.  You can wait for me or jump in and try to duplicate a pattern used for another header.

**Comment by hueniverse** [comment]
Is there still interest in this or can we close the issue?

**Comment by sholladay** [comment]
I would like this very much. For now, in order to decide whether the user would prefer HTML over JSON, my plugin checks whether `request.headers.accept` contains either `text/html` or `*/*` ([source code here](https://github.com/sholladay/hapi-error-page/blob/badf0bb3302f4bd5382f6011f4556cf655f7deb7/index.js#L11-L15)). This works generally, but I know it's not really correct.

I'd like to think I could contribute this at some point, but I'm not very familiar with the spec. Realistically, it wouldn't happen for a while. Any help would be much appreciated.
