### ISSUE TITLE
Complex media type with single preference results in inconsistent output

### ISSUE THREAD

**Issue by Lakitna** [hapijs/accept#52]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Community
* *is this issue currently blocking your project?* (yes/no): No
* *is this issue affecting a production system?* (yes/no): No

#### Context

* *node version*: 12.13.1
* *module version with issue*: 5.0.0
* *last module version without issue*: Unsure
* *environment* (e.g. node, browser, native): Node
* *used with* (e.g. hapi application, another framework, standalone, ...): Standalone
* *any other relevant information*:

#### What are you trying to achieve or the steps to reproduce?

We're using the Zalando API guidelines and one of the things in them is that versioning is done via media types. Because of this we are requesting with an Accept header like `application/json;version=2`.

[Zalando API guidelines rule: MUST use media type versioning](https://opensource.zalando.com/restful-api-guidelines/#114)

I wrote a validation to see if the received Accept header is of a version we can respond in. To do this I have a situation like below.

#### What was the result you got?

```js
const hapiAccept = require('@hapi/accept');

const result = hapiAccept.mediaType('application/json;version=2', ['application/json;version=2']);
// result = ''
```

The following will also return `''`:

```js
const result = hapiAccept.mediaType('application/json;foo=bar', ['application/json;foo=bar']);
// result = ''
```

The curious thing here is that the following DOES return as expected:

```js
const result = hapiAccept.mediaType('application/json;foo=bar', ['application/json;foo=bar', 'application/json']);
// result = 'application/json;foo=bar';
```

#### What result did you expect?

```js
const result = hapiAccept.mediaType('application/json;foo=bar', ['application/json;foo=bar']);
// result = 'application/json;foo=bar';
```

**Comment by hueniverse** [comment]
Preferences do not support param preference. It simply not implemented.

**Comment by Lakitna** [comment]
Which is the reason for this issue.

I could add the feature on my end, but I feel like it should live here instead.

**Comment by hueniverse** [comment]
Are you using this module as part of a hapi application or on its own?

**Comment by Lakitna** [comment]
I'm using it standalone

**Comment by hueniverse** [comment]
They way it is used by hapi application, this feature is not needed. I rather not add it as it is already complicated enough.

**Comment by Lakitna** [comment]
Makes sense.. I'll see if I can find another package that will suit my needs better, or implement this on my end.
